name: Build Flashable PocketPC JumpDrive SD Card Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install or Restore Required Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: u-boot-tools gcc-aarch64-linux-gnu g++-aarch64-linux-gnu mtools
        version: 1.0
    - name: Restore Download Cache
      uses: actions/cache/restore@v3
      with:
       path: build/
       key: build-dir
    - name: Compile JumpDrive SD Card Image
      run: make -j8 sourceparts-pocketpc.img
    - name: Prepare Build Artifacts & Perform Checksum
      working-directory: output/images
      run: sha256sum sourceparts-pocketpc.img > sourceparts-pocketpc.img.sha256sum
    - name: Save Download Cache
      uses: actions/cache/save@v3
      if: always()
      with:
        path: build/
        key: build-dir
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PocketPC_JumpDrive_Image
        path: |
          sourceparts-pocketpc.img
          sourceparts-pocketpc.img.sha256sum
