name: Build Flashable PocketPC JumpDrive SD Card Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install or Restore Required Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: u-boot-tools
        version: 1.0
   #- uses: webfactory/ssh-agent@v0.8.0
   #  with:
   #    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
   #    log-public-key: false
   #- name: Restore Download Cache
   #  uses: actions/cache/restore@v3
   #  with:
   #    path: |
   #      dl/
   #      output/
   #    key: dl-and-output-dir
    - name: Compile JumpDrive SD Card Image
      run: make -j8 sourceparts-pocketpc.img
   #- name: Save Download Cache
   #   uses: actions/cache/save@v3
   #   if: always()
   #   with:
   #     path: |
   #       dl/
   #       output/
   #     key: dl-and-output-dir
   # - name: Prepare Build Artifacts & Perform Checksum
   #   working-directory: output/images
   #   run: |
   #     rm -rf .empty
   #     cp ../../flash.sh .
   #     sha256sum * > checksums.txt
   # - name: Upload Build Artifacts
   #   uses: actions/upload-artifact@v3
   #   with:
   #     name: build_output_images
   #     path: output/images/
   # - name: Save Download Cache
   #   uses: actions/cache/save@v3
   #   if: always()
   #   with:
   #     path: |
   #       dl/
   #       output/
   #     key: dl-and-output-dir
   # - name: Prepare Build Artifacts & Perform Checksum
   #   working-directory: output/images
   #   run: |
   #     rm -rf .empty
   #     cp ../../flash.sh .
   #     sha256sum * > checksums.txt
   # - name: Upload Build Artifacts
   #   uses: actions/upload-artifact@v3
   #   with:
   #     name: build_output_images
   #     path: output/images/
